### ISSUE TITLE
Loading file created with default OCIO config crashes

### ISSUE THREAD

**Issue by Italic-** [sobotka/filmic-blender#1]
I've had a repeatable crash when working with this OCIO config and the VSE. Specifically, I have an older file created with another config (I've used both bassam-test and those shipped with blender), and loading the file or starting playback in the VSE will segfault. I've gotten errors on both Windows and Linux. Windows gives me the error EXCEPTION_ACCESS_VIOLATION, and Linux gives me a segfault. I am also unable to create a file in filmic config and open in default.

Oddly, I only get problems with _this_ config, not bassam-test. With bassam-test I can go back and forth without issue.
[filmic_test.blend.zip](https://github.com/sobotka/filmic-blender/files/621155/filmic_test.blend.zip)

**Comment by Italic-** [comment]
I suppose I should specify how to use the attached file. The test file is created in default 2.78a. Replace 2.78a's config with filmic and load the file again. It should crash. Likewise, create a similar file in filmic, then open it in default and it should also crash.

**Comment by sobotka** [comment]
Segfault is always a no-go. File the report under this or a new one. https://developer.blender.org/T50122

**Comment by Italic-** [comment]
This has been fixed with Sergey's [OCIO fix](https://developer.blender.org/rB1b9cae9d04c222d1ce8dc05abbd5692c30fe3e57) in blender source. Closing.
