### ISSUE TITLE
Repository does not include license information

### ISSUE THREAD

**Issue by eriknstr** [sobotka/filmic-blender#10]
Please select an appropriate license for your work and add it to the repository.

I suggest using the GPLv2 license in this case since that would make it simple to distribute Filmic Blender together with Blender in situations where that is desired since Blender itself is using the GPLv2 license.

**Comment by mgmillani** [comment]
Why GPLv2 and not GPLv3?

**Comment by eriknstr** [comment]
Because Blender itself is using the GPLv2 license.

**Comment by eriknstr** [comment]
https://www.blender.org/about/license/

**Comment by mgmillani** [comment]
That page also states:

> All the components that together make Blender are compatible under the newer GNU GPL Version 3. That is also the license to use for any distribution of Blender binaries.

**Comment by sobotka** [comment]
When I read license concerns, I read it as trolling.

I am contemplating making the transform set copyrighted and subject to the Linux Only License (LOL).

Focus on shit that matters; making compelling work.
