### ISSUE TITLE
exr format

### ISSUE THREAD

**Issue by thedaemon** [sobotka/filmic-blender#11]
It seems that all of the 32bit or 16bit data is not getting exported to exr format correctly.

This is take from another user as I don't have Nuke.

"Screenshot in Natron... Both images are converted to CINEON Log Space then i crankt up the fstops... Filmic Blender has serious issues with deep blacks... in a 16 or 32 bit working enviroment is filmic blender not a good sollution it kills dynamic range..."
![bildschirmfoto_vom_2017-02-17_212511](https://cloud.githubusercontent.com/assets/10872386/23083844/def95ce4-f51c-11e6-82d1-919bedb9c6e5.png)

**Comment by sobotka** [comment]
Before trying to establish an intra-pipeline process, I would encourage you to master the lower level mechanics first. Happy to help once you have done that.

You can't mix and match encoded transfer functions.
