### ISSUE TITLE
Not working on Arch Linux installed Blender (community repository)

### ISSUE THREAD

**Issue by ChameleonScales** [sobotka/filmic-blender#13]
I can't get filmic to work on my installed Blender on Linux Manjaro.
It works on a Blender 2.78b tar.bz version downloaded from blender.org but not on a 2.78b version installed from the Arch community repository.
Although all the filmic options are here, the colors don't change at all no matter what I choose. I don't get proper desaturation or anything else.

![screenshot_20170218_173733](https://cloud.githubusercontent.com/assets/19158847/23094896/5326059c-f601-11e6-912b-968376b49743.jpg)

Specs :
Linux Manjaro 16.10.3 64-bit

**Comment by sobotka** [comment]
This appears to be a preexisting image file loaded from disk?

**Comment by ChameleonScales** [comment]
No it's just rendered and the viewport gives the same result in Render mode.

**Comment by sobotka** [comment]
Must be something local to your installation. Try a clean installation of Blender via download and set the environment variable.

It isn't the configuration as best as I can see there.

**Comment by mzpsh** [comment]
Im using Arch, and it is working

![2017-02-25_14-57-22_scrot](https://cloud.githubusercontent.com/assets/7564816/23329055/d773154c-fb6a-11e6-8add-5afef5218f29.png)

**Comment by sobotka** [comment]
Given no progress on this, and the likelihood that it is a local issue, closing for now.

**Comment by ChameleonScales** [comment]
I just tried on a different computer, in a freshly installed, latest XFCE Manjaro and now even the filmic options don't appear. I get empty dropdown menus. Maybe I went fast saying it's an Arch problem, but I think it's a Manjaro problem, rather than just specific to my computer.

**Comment by leestripp** [comment]
I run Manjaro and it works fine, but never use the AUR version or the supplied Manjaro version of Blender. Whoever is building them has no clue. Get Blender from blender.org and you should be fine.

**Comment by Mateusz-Grzelinski** [comment]
In my case (frash install on Manjaro XFCE) I manually copied filmic files to it's destination (/usr/share/blender/2.78/datafiles/colormanagement) and it didn't seem to work. The error was: could not read /usr/share/blender/2.78/datafiles/colormanagement OCIO profile
What I did was to run blender as root. 
sudo blender
Worked...

**Comment by leestripp** [comment]
You should never run Blender as root, best to install blender into your home dir. say: /home/bin/blender then add to PATH. copy filmic over and your done.
