### ISSUE TITLE
Not Working Under Cycles On Linux Debian 8.7.1 64bit

### ISSUE THREAD

**Issue by ThatGuyWhoUsesLinux** [sobotka/filmic-blender#15]
Using a fresh install of Blender 2.78b with Filmic Blender installed, and I seemingly can't get Filmic Blender to affect how my scenes when using Cycles. Works fine under the internal renderer, but there is absolutely no change to the colours in my scene when switching to Cycles, the scene doesn't even refresh when changing the options around.
Here's a short clip of this in action: ![blenderfilmicissuedemo](https://cloud.githubusercontent.com/assets/25926840/23164434/d2d9c9cc-f7eb-11e6-9eaf-f332255de5bb.gif)
Any user preferences or plugins that are potentially interfering? Is there more setup needed than just replacing the colormanagment directory?

**Comment by MisterGoodMorning** [comment]
Check your colormanagement folder and subfolders permissions. Access was denied on them when i checked. I just change the permission through terminal on Ubuntu Studio 16.04. with the following code:

sudo chmod -R 755 /usr/share/blender/2.78/datafiles/colormanagement

The path to colormanagement folder might be different on your OS so use yours instead of mine.
Hope this helps you.

**Comment by ThatGuyWhoUsesLinux** [comment]
The permissions seemed alright, tried it nonetheless. Unfortunately nothing has changed.

**Comment by MisterGoodMorning** [comment]
Did you try rendering with gpu or cpu? Gpu wont work for me in realtime render.

-----Izvorna poruka-----
Šalje: "ThatGuyWhoUsesLinux" <notifications@github.com>
Poslano: ‎21.‎2.‎2017. 18:04
Prima: "sobotka/filmic-blender" <filmic-blender@noreply.github.com>
Kopija: "MisterGoodMorning" <cyberzivac@gmail.com>; "Comment" <comment@noreply.github.com>
Predmet: Re: [sobotka/filmic-blender] Not Working Under Cycles On Linux Debian8.7.1 64bit (#15)

The permissions seemed alright, tried it nonetheless. Unfortunately nothing has changed.

**Comment by ThatGuyWhoUsesLinux** [comment]
I rendered with the CPU, I don't have a GPU. I heard the open source video drivers don't support my CPU very well, that potentially could be the issue.

**Comment by sobotka** [comment]
It would seem that it isn't an issue with the configuration itself. Best advice is to try an environment variable such as:
    export OCIO=/path/to/downloaded/Filmic/config.ocio

**Comment by ThatGuyWhoUsesLinux** [comment]
I still have have this issue even when using environment variables. I think Filmic Blender lacks some compatibility on certain setups and this should be looked into further.

**Comment by sobotka** [comment]
I develop using OCIO using environment variables. I don't believe there are any issues.

**Comment by ThatGuyWhoUsesLinux** [comment]
If it is not working properly under certain hardware/software configurations for no foreseeable reason than there is an issue.

**Comment by sobotka** [comment]
Yes it is a configuration. Yes it is built on top of a library in use in many post houses.

Is there an issue on your end? Sure.

Is it an issue with OpenColorIO or the passive configuration? There is a chance, albeit a very, very, small one.

What is the issue exactly? What have you tried?
