### ISSUE TITLE
Submit as a patch for Blender?

### ISSUE THREAD

**Issue by draeath** [sobotka/filmic-blender#18]
Not really an issue per-se, but I don't see why these changes shouldn't be considered for inclusion into blender as a patch. Has this been looked at?

**Comment by benrob0329** [comment]
It's going to be in 2.79.

**Comment by sobotka** [comment]
I am not super keen on having it integrated into Blender proper in the current state. This is due to the default configuration needing a cleaning. Mixing and matching transforms is a mess.

**Comment by supersammy7000** [comment]
I heard that it might be added in 2.78c
