### ISSUE TITLE
Loading file created with default OCIO config crashes VSE

### ISSUE THREAD

**Issue by aceman500** [sobotka/filmic-blender#19]
I am having the same problem described in an old closed issue by Italic.
When I load a blend file created with the blender shipped color config and switch to the VSE or if the VSE is open on load it crashes blender. (seg fault)
It seems there must be saved tracks in the VSE for this to ocour. A  blend file loaded with noting in the VSE has no problems when you switch to it.
I am using Blender 278b

**Comment by sobotka** [comment]
I believe this was fixed in trunk. If you have a means to check trunk, that would be most ideal. If it is not, it would require a new report at developer.blender.org with a minimal example in order for Sergey or someone to repair it. Are you able to test a trunk build?

**Comment by aceman500** [comment]
No I have not but i'm sure I figure it out. So does this mean that Sergey's fix it's not merged into the version of blender I have?

**Comment by sobotka** [comment]
It may be. You would have to check the hash of the build you have against the hash of the fix. Upper right corner of the splash screen shows you the build version you are on. There are builds available at https://builder.blender.org.

**Comment by aceman500** [comment]
Thanks very mush for the help. It works ok with the latest build. Sorry for the bother..

**Comment by sobotka** [comment]
No problem. Thanks for testing.
