### ISSUE TITLE
please i just recently started using linux and havent a clue how i add flimic-blender to my OS. can someone take time to help me through this. 

### ISSUE THREAD

**Issue by lisabiziou** [sobotka/filmic-blender#21]

**Comment by sobotka** [comment]
I'm going to close this issue, as it doesn't quite fit the requirements for an issue unto itself.

There is already an issue with solutions provided for MacOS, as well as quite a few tutorials out there for Windows.

If you are still having trouble, please post your question to http://blender.stackexchange.com/ and ask how to install custom OpenColorIO configurations under Blender. If you specifically mention Filmic, it may be closed as off-topic by the moderators, while OpenColorIO is a generic and crucial part of Blender proper.
