### ISSUE TITLE
[Q] Why are a lot of images clipped on the whites

### ISSUE THREAD

**Issue by schroef** [sobotka/filmic-blender#23]
Im using Filmic together with Thea Render, thats a different renderer then cycles for Blender. Im wondering why most of the images i use with Filmic have the whites "clipped". The range of white doesnt extend to the end of the histogram?

Blender and Photoshop show the same result. It can be fixed easily ofcourse. But im wondering why all images show it
<img width="199" alt="blender_histogram" src="https://cloud.githubusercontent.com/assets/6923008/23553186/1da4882c-fff6-11e6-8a10-eeb81660ab4e.png">
<img width="266" alt="photoshop_histogram" src="https://cloud.githubusercontent.com/assets/6923008/23553185/1da32496-fff6-11e6-8c97-e3adb7833216.png">

**Comment by sobotka** [comment]
This is off topic so I am closing. I am happy to try and help though.

Your renderer isn't getting you the highest values that Filmic permits. As a start, increase the illumination and see if you can get a light in the frame to sit higher in the output.

**Comment by schroef** [comment]
Why is this off topic? This is related to Filmic right as i see it or is it cause i use different renderer?
