### ISSUE TITLE
Video Sequence Editor - crashes Blender

### ISSUE THREAD

**Issue by adamthomasgoss** [sobotka/filmic-blender#24]
This may be covered in another issue, but in case I missed it, the video sequence editor currently doesn't work with the filmic-blender colorspace. Even when I set the colorspace to sRGB EOTF the video sequence editor won't load (Blender crashes). This really isn't a production blocker, as it's easy to have a second instance of Blender without filmic-blender.

I'm running MacOS Sierra 10.12.3 and Blender 2.78b

PS, thanks for this project. Filmic-blender is amazing.

**Comment by sobotka** [comment]
This happened to be issue #1

Should be fixed in trunk.
