### ISSUE TITLE
Filmic Blender on Maya 2017 error.

### ISSUE THREAD

**Issue by tkio-64** [sobotka/filmic-blender#26]
Hello,

I tried uncommenting all the line to use in Maya but still get this message:

"config.ocio failed. yaml-cpp: error at line 47, columm 5: illegal block entry".

I use Maya 2017 update 2 by the way. At work with the same config on update 3, it works fine.
Great work by the way. Thank you.

J.

**Comment by sobotka** [comment]
Check whitespace?

I don't think there is anything I can do on this end other than to verify that the whitespace and indentation is clean. OCIO can be very fussy on that front.

**Comment by tkio-64** [comment]
Thank you Troy. I forgot about that one. I'll check and let you know.

J.

**Comment by ChameleonScales** [comment]
Sorry but this really peaked my curiosity. What render engine are you doing this on ?

**Comment by tkio-64** [comment]
It fixed the problem Troy. Thank you.
I'm using Arnold ChameleonScales. 

J.

**Comment by sobotka** [comment]
Happy to hear it was sorted. Hopefully like minded Maya folks can continue to use this thread. Closing.
