### ISSUE TITLE
Headless render error 

### ISSUE THREAD

**Issue by aankruwet** [sobotka/filmic-blender#28]
Hello 

thanks for your awesome tools man . . .

its helps me a lot 

but recenly we have some issue when we render our scene in headless mode (command promp) 
its suddenly error here the output from cmd : 

c:\Program Files\Blender Foundation\Blender>blender -E CYCLES -b F:\RENDER\SH25\ANM_SQ005_SH0025.blend -o F:\RENDER\
Color management: display "sRGB" used by scene not found, setting to default ("sRGB / BT.709").
Color management: scene view "Default" not found, setting default "sRGB EOTF".
Color management: sequencer colorspace "sRGB" not found, will use default instead.
Read new prefs: C:\Users\***\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend
found bundled python: c:\Program Files\Blender Foundation\Blender\2.78\python
read blend: F:\RENDER\SH25\ANM_SQ005_SH0025.blend
Info: Read library:  'Z:\Char_1.blend', parent '<direct>'
Info: Read library:  'Z:\Char_2.blend', 'Z:\Char_3.blend', parent '<direct>'
Info: Read library:  'Z:\Char_4.blend', 'Z:\Char_4.blend', parent '<direct>'
Info: Read library:  Z:\Char_5.blend', parent '<direct>'
Info: Read library:  'Z:\Char_6.blend', 'Z:\Char_7.blend', parent '<direct>'
Dependency cycle detected:
  Plane.008 depends on Char_rig through Armature Modifier.
  Char_rig depends on Plane.008 through Action.

Color management: display "sRGB" used by scene not found, setting to default ("sRGB / BT.709").
Color management: scene view "Default" not found, setting default "sRGB EOTF".
Color management: sequencer colorspace "sRGB" not found, will use default instead.
Color management: image colorspace "sRGB" not found, will use default instead.
Color management: image colorspace "sRGB" not found, will use default instead.
Color management: image colorspace "sRGB" not found, will use default instead.
Color management: image colorspace "sRGB" not found, will use default instead.

Blender quit

**Comment by sobotka** [comment]
Unrelated to the OCIO configuration.

**Comment by CowanCS1** [comment]
I have the same issue. The system defaults to the first option listed in the config.ocio file, so you can still select Filmic Log Encoding by swapping that to the first view in the list under "sRGB / BT.709".

**Comment by sobotka** [comment]
The sRGB transform is first in the configuration due to some painting strangeness reported long ago.
