### ISSUE TITLE
Eastman Double X Neg 4min, Agfa Agfacolor Vista 800, ect

### ISSUE THREAD

**Issue by brontosaurusrex** [sobotka/filmic-blender#30]
What would it take to plug those film looks into this?

**Comment by sobotka** [comment]
Never going to happen.

The original data set isn't clear on the log intensities nor the primaries. That makes the transforms utter junk and worthless.

Instead, use the CDL to generate custom looks, and add them to the configuration.

**Comment by brontosaurusrex** [comment]
You mean the compositor effects? (That will not work in viewport, so pretty useless)

**Comment by sobotka** [comment]
It isn't an effect, but rather a standard method of grading. You can "can" CDLs for re-use in looks, so a small investment of time ends up building a library of unique and custom looks.

**Comment by brontosaurusrex** [comment]
I guess this is a workflow question. Mine is like:
preview render (I love the color management due to the fact that is active in viewport render) > render to exr > post in something else (sometimes mimicking stuff that happened in preview, sometimes not). 
Unless I'am missing some knowhow?

**Comment by sobotka** [comment]
Again, with CDL values, you can generate a custom look for use with OCIO. That means you can use and reuse it just as you would the previous Instagram-esque random looks. I hope to include a demo version as an example in an upcoming branch.

**Comment by brontosaurusrex** [comment]
^ great, now I get it (and have bunch of reading to-do).
