### ISSUE TITLE
Uncommenting views on lines 39 to 47 in config.ocio leaves them missing one space

### ISSUE THREAD

**Issue by chrisoffner3d** [sobotka/filmic-blender#31]
When I uncomment [these lines](https://github.com/sobotka/filmic-blender/blob/master/config.ocio#L39-L47) I get errors on importing the file to NUKE because the lines then lack a space each.

**Comment by sobotka** [comment]
Just looked into this again. From what I can count when I check the whitespace on the lines linked, it seems correct? Am I hallucinating?

**Comment by maximeroz** [comment]
Working just fine for me in NUKE.

**Comment by sobotka** [comment]
Chris, this is fine in trunk yes?

**Comment by sobotka** [comment]
I'm going to close this as it seems that things should be working? If there is an issue, feel free to reopen.
