### ISSUE TITLE
Ubuntu 16.04 Installation

### ISSUE THREAD

**Issue by DukeOfMarshall** [sobotka/filmic-blender#32]
Good morning! I have just installed Filmic Blender on my Windows 10 installation and been playing around with it. (LOVE IT by the way) But now I'm trying to install it on one of my Ubuntu installations and coming up with a blank. I tried searching for the "colormanagement" folder to no avail. I searched for the ".icio" file and found nothing. The Blender folder on Ubuntu seems not to have what I need (or what I think I need).

Does anyone have any advice or assistance on how to install Filmic Blender on Ubuntu 16? Thanks.

**Comment by sobotka** [comment]
The easiest technique is to use the environment variable approach.

```
export OCIO=/path/to/Filmic/config.ocio
```

Other than that, there is likely a local directory for configuration settings, but it is beyond the scope of the configuration itself.

Hope this helps.

**Comment by DukeOfMarshall** [comment]
Thanks for the reply and the information. I started to do that and then finally found the colormanagement folder. For some reason it didn't show up in the search I did earlier. Possibly something to do with permissions maybe?

Anyways, here is the terminal output of what I did and I can confirm that filmic blender is working for me now on Ubuntu 16.04 with Blender 2.76b. Just in case anyone else might be able to use this information in the future.



>>`
>>user@computer:~$ echo $OCIO
>>
>>user@computer:~ $ whereis blender
>>blender: /usr/bin/blender /usr/share/blender /usr/share/man/man1/blender.1.gz
>>user@computer:~ $ cd Downloads/
>>user@computer:~ /Downloads $ sudo unzip filmic-blender-master.zip -d /usr/share/blender/datafiles/
>>[sudo] password for user: 
>>Archive:  filmic-blender-master.zip
>>6f537f682f43b110cd2027fa514da2333899c194
>>   creating: /usr/share/blender/datafiles/filmic-blender-master/
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/README.md  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/_config.yml  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/config.ocio  
>> extracting: /usr/share/blender/datafiles/filmic-blender-master/index.md  
>>   creating: /usr/share/blender/datafiles/filmic-blender-master/looks/
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_False_Colour.spi3d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_to_0-35_1-30.spi1d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_to_0-48_1-09.spi1d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_to_0-60_1-04.spi1d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_to_0-70_1-03.spi1d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_to_0-85_1-011.spi1d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_to_0.99_1-0075.spi1d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/looks/Filmic_to_1.20_1-00.spi1d  
>>   creating: /usr/share/blender/datafiles/filmic-blender-master/luts/
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/luts/BT.1886_to_Linear.spi1d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/luts/desat65cube.spi3d  
>>  inflating: /usr/share/blender/datafiles/filmic-blender-master/luts/sRGB_OETF_to_Linear.spi1d  
>>user@computer:~ /Downloads $ sudo mv /usr/share/blender/datafiles/colormanagement >>/usr/share/blender/datafiles/colormanagement2
>>user@computer:~  /Downloads $ sudo mv /usr/share/blender/datafiles/filmic-blender-master >>/usr/share/blender/datafiles/colormanagement 
`
