### ISSUE TITLE
updating instructions

### ISSUE THREAD

**Issue by scottpetrovic** [sobotka/filmic-blender#37]
I notice that blender is recently starting to include Filmic in Blender. I just got the 2.79 RC1. I am not sure if it contains everything in your repo though

The Blender RC includes the looks, but puts it in a "filmic" folder . I cannot tell if the luts are all in there. Maybe they renamed some of the stuff. 

At the least, it is a heads up that the instructions might need to change. If blender is keeping the up to date versions, the instructions can just say that "filmic is included in blender by default starting with version 2.xx".  I haven't tried 2.78, so maybe it is in that as well.

Glad to see this is being so well received. You deserve the attention and praise!

**Comment by sobotka** [comment]
The integration in Blender upstream is slightly different from this implementation in the repository. The reason for the differences is based on a difference of opinion as to what qualifies as a Look. I'm not too interested in debating the issue, but if you want to read my views on it, you can find them on the Blender Developer list.

Hope this helps.
