### ISSUE TITLE
Installed new colormanagement folder, no results

### ISSUE THREAD

**Issue by TombstoneTumbleweedArt** [sobotka/filmic-blender#4]
Followed install instructions but only get default color options.  Did a clean reinstall of 2.78a, replaced colormanagement folder with Filmic - same result.  Noticed Blender startup console window did not report expected "could not find sRGB" etc.

**Comment by sobotka** [comment]
It works on a full copy of the entire directory.

A cleaner method is to use environment variables.

If this is a challenge, perhaps members of the community can help further with the basics of OCIO, such as asking on blender.stackexchange.com or blenderartists.org.

**Comment by TombstoneTumbleweedArt** [comment]
Hello!


Thank you for the response!


It turns out that on my install of Win 8.1, although the colormanagement folder is indeed where it should be inside of Program Files/Blender Foundation/..., there is in fact ANOTHER colormanagement folder under Users, and it was in this duplicate directory that I had to paste the Filmic files.  Yay, it works!


The full path is:


C:\Users\Michael\AppData\Roaming\Blender Foundation\Blender\2.78\datafiles\colormanagement


Thank you very much, Troy! [😊]



________________________________

**Comment by flakjakk** [comment]
I'm having exactly this same issue - Win7 64bit. Although I copied the directory into both Program files and User folder locations it still doesn't work. Any ideas?

**Comment by sobotka** [comment]
While copying and pasting *can* work, I would encourage everyone to use the environment variable approach as it can be much cleaner.

I suspect that every incarnation of Windows might have a varying directory for the proper destination.

**Comment by flakjakk** [comment]
Using the env var worked perfectly. Thanks so much. Can't wait to get into the sw.
