### ISSUE TITLE
Create an initial release / tag for stable versions in order to use in pipelines

### ISSUE THREAD

**Issue by Aadjou** [sobotka/filmic-blender#41]
First of all, thanks for the great work. It's really amazing what this can do for artists!

We want to use filmic-blender in our automated command-line application that is rendering things with blender. 
To set up the process, we currently load the addon directly from the source from the master branch. 
For versioning and stability of our process, it would be fantastic to have github releases or tags for each stable version.

Thank you

**Comment by sobotka** [comment]
Thanks for the feedback. Version 1.0.0 now tagged at head.

**Comment by Aadjou** [comment]
Thank you!
