### ISSUE TITLE
Lighting not working 

### ISSUE THREAD

**Issue by NoahH240** [sobotka/filmic-blender#46]
I went to test it with a regular cube on base contrast, but when I rendered it all but few of its faces were completely black. Is thee any way to fix this?

**Comment by sobotka** [comment]
This is a geometry issue and has nothing to do with the configuration. Sorry.

**Comment by Serkan-devel** [comment]
Have you set the color seetinfs from sRGB to filmic or something?

**Comment by Serkan-devel** [comment]
nvm the comments loaded later for some odd reason
