### ISSUE TITLE
No Apple DCI-P3 View Transforms

### ISSUE THREAD

**Issue by sobotka** [sobotka/filmic-blender#47]
All iMacs from late 2015 and all MacBooks and MacBook Pros from 2016 onwards use wider gamut displays. Filmic doesn't currently support them.

**Comment by JamesSylvester** [comment]
Hi @sobotka. Thanks for the new view transforms. I have downloaded the Apple p3 branch and will do some tests with it over the next week or so and let you know how it goes.
