### ISSUE TITLE
Blender 2.8

### ISSUE THREAD

**Issue by MontgomeryDixon** [sobotka/filmic-blender#54]
In the 20 May 2019 meeting notes it was stated:
> The OpenColorIO color management configuration was updated to remove legacy transforms. This provides a clean base for future improvements. (Brecht Van Lommel)
> * Replace Log view transform with Filmic Log.
> * Remove Rec.709, DCI-P3 displays that were incomplete and outdated.
> * Remove outdated RRT and Film transforms, replaced by Filmic.
> * Remove camera responsive curves that don’t work with HDR colors.
> * Rename Default view transform to Standard.
So following this commit to Blender, what are the differences in color management between 2.8 and this repository?

**Comment by sobotka** [comment]
Indeed. Baby steps to progress...

**Comment by MontgomeryDixon** [comment]
So what differences remain in color management between 2.8 master and this repository?

**Comment by sobotka** [comment]
I’m not sure Brecht updated the False colour. Blender `master` also doesn’t include the proper transforms for Apple Display P3 devices, which is a majority of Apple displays since 2015. I’ll be adding the broadcast BT.1886 Display as well shortly.

Still quite a few ugly messes in `master` at Blender.

**Comment by MontgomeryDixon** [comment]
Thanks. I will continue using filmic-blender. Does filmic-blender work in 2.8 too?

**Comment by sobotka** [comment]
It should. If it doesn’t, that’s up to you folks to let me know if it is broken, or let the Blender people know where their OpenColorIO chain is broken.
