### ISSUE TITLE
Blender V2.79 "Default" view for filmic blender

### ISSUE THREAD

**Issue by NewInTheRoom42** [sobotka/filmic-blender#55]
To sum it up and save time? I followed all of the appropriate steps up until testing the feature out. When I went to render>view it only displayed default. Nothing else. Apparently it is an issue with Blender itself and there is nothing I can do about that. However, if there is please update me. I'm a new and enthusiastic Blender fan and was dying to try this out. Thank you, have an amazing day/night.

**Comment by sobotka** [comment]
Not sure what the issue is here. I’ll reopen if you can make it clearer.
