### ISSUE TITLE
Dumb Newbie Question.

### ISSUE THREAD

**Issue by r2rangel** [sobotka/filmic-blender#58]
The default color management in 2.8 is now filmic, so I'm assuming that blender 2.8 comes with filmic-blender right ? I Just want to be sure, and also install the right filmic-blender. So is blender 2.8 filmc, the same as sobotka filmic-blender ?

**Comment by sobotka** [comment]
There are some differences. The one here has a more refined false colour, and supports displays other than generic sRGB. I’ll close this, but feel free to ask more questions as needed.
