### ISSUE TITLE
 pasted 

### ISSUE THREAD

**Issue by mikegem72** [sobotka/filmic-blender#6]
I deleted original files and copy and pasted files no change, I uninstalled manually and installed manually then copy, pasted no change.  I used Blender Uninstaller and installer etc. no change.  I deleted original files and ran with empty colormanagement folder same no change. I downloaded new Blender (same as I was using 2.78a) no change.  I have only seen one other person on YouTube mention this problem(same one that posted here) so it must be something on my end, but no clue what it could be.  Download unzip was 15.1 MB all five or six of them, no luck.  Really look forward to trying this though,

**Comment by sobotka** [comment]
It works on a full copy of the entire directory.

A cleaner method is to use environment variables.

If this is a challenge, perhaps members of the community can help further with the basics of OCIO, such as asking on blender.stackexchange.com or blenderartists.org.
