### ISSUE TITLE
BlenderGIS Not working with FIlmic Blender

### ISSUE THREAD

**Issue by vikista** [sobotka/filmic-blender#62]
https://github.com/domlysz/BlenderGIS
![Problem](https://user-images.githubusercontent.com/68424155/87775787-f3a1c880-c826-11ea-9d57-eaeedf61c2ea.png)

**Comment by sobotka** [comment]
That’s their problem for hard coding a colourspace. They should have used roles.

**Comment by vikista** [comment]
Okay thx for answering my question. I'm going to write them. And thx for
Filmic Blender <3

pi 17. 7. 2020 o 16:40 Troy James Sobotka <notifications@github.com>
napísal(a):

**Comment by sobotka** [comment]
Any time. Kick ass with it.
