### ISSUE TITLE
Filmic Blender clipping color picker values.

### ISSUE THREAD

**Issue by mantissa-** [sobotka/filmic-blender#7]
This one is easy to reproduce.
When picking a color of a shader, values above 1.0 are not registered.
The RGB sliders can go above 1.0 but it doesn't affect the render.
The Value (HSV) slider bugs out when trying to go over 1.0 and resets to 1.0.
I use this quite a lot to boost refractions and reflections, would be nice if this was fixed.

And yes, I know it's not PBR, but I don't care. ;)

**Comment by sobotka** [comment]
Most shaders are bounded ranges. For example, the poorly named "Diffuse Colour" is actually an albedo that measures reflectance from 0.0 to 1.0.

Emissions, colour pickers, curves, etc. are another matter, and the only solution (and a solution in the larger sense) is to permit the imager to select the transform required *on each UI element*.

So while I would love to fix this, I can't.

It requires educated imagers to go and post bug reports on the Blender proper bug report listing. To do this properly, it requires knowing which shaders require infinite values, and how to properly address the issues (Hint: See above. :) )

Good luck. Part of the reason I created the set was to help imagers along the learning path with the hopes that these sorts of issues get more attention.
