### ISSUE TITLE
baking gets darker

### ISSUE THREAD

**Issue by ChameleonScales** [sobotka/filmic-blender#8]
If I bake an object's "Diffuse Color", the result gets darker than the original texture, which doesn't happen with Blender's original color management. I tried different settings but all of them gave darker results. Did I miss the correct setting ?

**Comment by sobotka** [comment]
There isn't quite enough information present here to offer a diagnosis. I would encourage you to create a minimal proof of principle, and post it as a but at developer.blender.org to see if this is a broken colour management path in Blender.
